name: Demloy 1

on:
  push:
  workflow_dispatch:
   
jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
      
      #- name: Cancel Duplicate Workflow Runs
      #  uses: styfle/cancel-workflow-action@0.9.0
      #  with:
      #    all_but_latest: true
      #    access_token: ${{ github.token }}

      #- name: Cleanup & Storage 75GB wait for the 7 minutes
      #  uses: rokibhasansagar/slimhub_actions@main
      
      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${{ secrets.GHMAIL }}
          git config --global user.name ${{ secrets.GHUSER }}
          git config --global credential.helper store
          echo "https://${{ secrets.GHUSER }}:${{ secrets.GHTOKENMAIN }}@github.com" > ~/.git-credentials

      - name: Clone Mirror Repository
        run: |
          git clone https://${{ secrets.GHTOKENMAIN }}@github.com/${{ secrets.GHUSER }}/${{ secrets.REPO }} source

      - name: Compile Docker
        run: |
          cd source && wget ${{ secrets.CONFIG_FILE_URL1 }} || exit 1
          docker container prune --force || true
          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t bot

      - name: Fast Deploy Bot is Runing
        continue-on-error: true
        timeout-minutes: 120
        run: |
          docker run --privileged --rm -i bot

      - name: Loop Workflow & Run again the Bot
        continue-on-error: true
        run: |
          git clone https://${{ secrets.GHTOKENCURRENT }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          git commit --allow-empty -m "Workflow: Loop"
          git push -f